- name: Cryptomator | Download AppImage
  get_url:
    url: https://dl.bintray.com/cryptomator/cryptomator/1.4.15/cryptomator-1.4.15-x86_64.AppImage
    dest: /opt/Cryptomator.AppImage
    mode: 'a+x'
  become: true

- name: Cryptomator | Copy Desktop file
  copy:
    src: applications/cryptomator.desktop
    dest: "{{ applications_dir }}/crytomator.desktop"
