- name: ENsure Promtail config exists
  ansible.builtin.file:
    path: /etc/promtail
    mode: "0755"
    state: directory
  become: true
  
- name: Promtail | Create Promtail configuration file
  ansible.builtin.template:
    dest: /etc/promtail/promtail-local-config.yml
    mode: '0644'
    src: promtail-local-config.yml.j2
  become: true

- name: Start container
  community.docker.docker_container:
    name: promtail
    image: grafana/promtail:3.0.1
    command: -config.file=/etc/promtail/config.yml
    labels:
      traefik.enable: 'false'
    networks:
      - name: monitoring
    restart_policy: unless-stopped
    state: started
    volumes:
      - /etc/promtail/promtail-local-config.yml:/etc/promtail/config.yml:ro
      - /var/log:/var/log:ro
      - /var/log/journal:/var/log/journal:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
