- name: YADM | Add repository
  command: dnf config-manager --add-repo https://download.opensuse.org/repositories/home:TheLocehiliosan:yadm/Fedora_33/home:TheLocehiliosan:yadm.repo
  args:
    warn: false
    creates: /etc/yum.repos/yadm.repo
  become: true

- name: Installs yadm
  dnf:
    name: yadm
    state: present
  become: true

- name: Dotfiles | Clone Repository
  command: yadm clone -f "{{ dotfiles_repo_url }}"
  args:
    creates: "{{ ansible_env.HOME }}/.config/.yadm"

- name: Dotfiles | Decrypt
  command: yadm decrypt

- name: Dotfiles | Update remote url to ssh
  command: yadm remote set-url origin "{{ dotfiles_ssh_repo_url }}"

- name: Dotfiles | Fix netrc permissions
  file:
    path: "{{ ansible_env.HOME }}/.netrc"
    mode: "0600"
  become: true
