- name: Install dnf plugins
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - dnf-plugins-core
    - libdnf5-plugin-actions
  become: true
- name: Install core packages
  ansible.builtin.dnf:
    name:
      - curl
      - wget
      - unzip
      - python-psutil
      - make
      - pwgen
      - lnav
      - httpie
      - htop
      - iotop
      - ncdu
      - tree
      - figlet
    state: present
  become: true
