- name: install the rpmfusion repo packages
  dnf:
    name:
      - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm
      - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm
    state: present
  become: true

- name: install the rpmsphere repo
  dnf:
    name: "https://github.com/rpmsphere/noarch/raw/master/r/rpmsphere-release-{{ ansible_distribution_version }}-1.noarch.rpm"
    state: present
  become: true

- name: upgrade system packages
  dnf:
    name: "*"
    state: latest # noqa 403
  become: true

- include: base.yml
- include: flatpak.yml
  tags: ["flatpak"]
- include: snapd.yml
  tags: ["snapd"]
- include: user.yml
- include: selinux.yml
