- name: install the rpmfusion repo packages
  dnf:
    name:
      - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm
      - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm
    state: present
  become: true

- name: install the rpmsphere repo
  dnf:
    name: "https://github.com/rpmsphere/noarch/raw/master/r/rpmsphere-release-{{ ansible_distribution_version }}-1.noarch.rpm"
    state: present
  become: true

- name: upgrade system packages
  dnf:
    name: "*"
    state: latest # noqa 403
  become: true

- import_tasks: base.yml
- import_tasks: flatpak.yml
  tags: ["flatpak"]
- import_tasks: snapd.yml
  tags: ["snapd"]
- import_tasks: user.yml
- import_tasks: selinux.yml
