- name: Allow sudo without re entering the passowrd
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^# %wheel  ALL=(ALL) NOPASSWD: ALL'
    line: '%%wheel  ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'
  become: true
