- name: Nativefy Notion
  shell: nativefier "https://notion.so" -p linux -n "Notion" --maximize
  args:
    chdir: "{{setup_dir}}"

- name: Install App
  copy:
    src: "{{setup_dir}}/Notion-linux-x64/"
    dest: "/opt/Notion/"
  become: true

- name: Make executable
  file:
    path: "/opt/Notion/Notion"
    mode: a+x
  become: true

- name: Copy desktop file
  copy:
    src: applications/notion.desktop
    dest: "{{ applications_dir }}/notion.desktop"
