- name: Check if Nativefier is installed
  command: which nativefdsier
  changed_when: false
  failed_when: nativefier_installed.rc not in [0,1]
  register: nativefier_installed

- name: Nativefy Notion
  comamnd: nativefier "https://notion.so" -p linux -n "Notion" --maximize
  args:
    chdir: "{{setup_dir}}"

- name: Install App
  copy:
    file: "{{setup_dir}}/Notion-linux-x64"
    dest: "/opt/Notion"
  become: true
