- name: Ticktick | Check if installed
  stat:
    path: /opt/TickTick
  register: ticktick_dir

- name: Ticktick | Nativefy
  shell: nativefier "https://www.ticktick.com/webapp" -p linux -n "TickTick" --maximize
  args:
    chdir: "{{setup_dir}}"
  when: not ticktick_dir.stat.exists

- name: TickTick | Install
  copy:
    src: "{{setup_dir}}/TickTick-linux-x64/"
    dest: "/opt/TickTick/"
  become: true
  when: not ticktick_dir.stat.exists

- name: TickTick | Fix application name
  shell: cat <<< $(jq '.name = "TickTick"' /opt/TickTick/resources/app/package.json ) > /opt/TickTick/resources/app/package.json
  become: true
  when: not ticktick_dir.stat.exists

- name: TickTick | make executable
  file:
    path: "/opt/TickTick/TickTick"
    mode: a+x
  become: true
  when: not ticktick_dir.stat.exists

- name: TickTick | Copy desktop file
  copy:
    src: applications/ticktick.desktop
    dest: "{{ applications_dir }}/ticktick.desktop"
  when: not ticktick_dir.stat.exists
