- name: Nativefy Notion
  shell: nativefier "https://www.ticktick.com/webapp" -p linux -n "TickTick" --maximize
  args:
    chdir: "{{setup_dir}}"

- name: Install App
  copy:
    src: "{{setup_dir}}/TickTick-linux-x64/"
    dest: "/opt/TickTick/"
  become: true

- name: Make executable
  file:
    path: "/opt/TickTick/tick-tick"
    mode: a+x
  become: true

- name: Copy desktop file
  copy:
    src: applications/ticktick.desktop
    dest: "{{ applications_dir }}/ticktick.desktop"
