- name: Download Rustup installation script
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: "{{setup_dir }}/rustup-init.sh"
    mode: '0755'

- name: Install Rustup
  ansible.builtin.shell: "{{ setup_dir }}/rustup-init.sh -y"
