- name: Ansible playbook to setup my local machine
  hosts: all

  vars_files:
    - vars/main.yml

  vars_prompt:
    - name: github_token
      prompt: "What is your GitHub Token?"
      default: "{{ lookup('env','GITHUB_TOKEN') }}"
      private: yes

  pre_tasks:
    - name: Ensure setup directory exists
      file:
        path: "{{ setup_dir }}"
        state: directory
        mode: 0755
      tags: [always]

  post_tasks:
    - name: Remove setup directory
      file:
        path: "{{ setup_dir }}"
        state: absent
      become: true
      tags: [always]

  handlers:
    - name: restart docker
      service:
        name: docker
        state: restarted
      become: true

  tasks:
    - import_tasks: tasks/system/main.yml
      tags: ["system"]

    - import_tasks: tasks/dotfiles.yml
      tags: ["dotfiles"]

    - import_tasks: tasks/shell/main.yml
      tags: ["shell"]

    - import_tasks: tasks/cli/main.yml
      tags: ["cli"]

    - import_tasks: tasks/internet/main.yml
      tags: ["internet"]

    - import_tasks: tasks/productivity/main.yml
      tags: ["productivity"]

    - import_tasks: tasks/utilities/main.yml
      tags: ["utilities"]

    - import_tasks: tasks/multimedia/main.yml
      tags: ["multimedia"]

    - import_tasks: tasks/dev/main.yml
      tags: ["dev"]

    - import_tasks: tasks/games/main.yml
      tags: ["games"]

    - import_tasks: tasks/network/main.yml
      tags: ["networking"]

    - import_tasks: tasks/desktop/main.yml
      tags: ["desktop"]

    - import_tasks: tasks/virtualization/main.yml
      tags: ["virtualization"]
