- name: AWS CLI | Download Installer
  ansible.builtin.unarchive:
    dest: /tmp
    mode: '0755'
    remote_src: true
    src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip

- name: AWS CLI | Run install command
  ansible.builtin.command: ./aws/install -i /usr/local/aws-cli -b /usr/local/bin --update
  args:
    chdir: /tmp
  become: true
