- name: Install Tailscale
  ansible.builtin.command: curl -fsSL https://tailscale.com/install.sh | sh
  become: true

- name: Enable Tailscale
  ansible.builtin.systemd:
    enabled: true
    name: tailscaled
    state: started
  become: true

