- name: Get Lastest Release
  community.general.github_release:
    action: latest_release
    user: rgwood
    repo: systemctl-tui
    token: '{{ github_token }}'
  register: release

- name: Download and Install
  ansible.builtin.unarchive:
    dest: '{{ bin_dir }}'
    remote_src: true
    src: https://github.com/rgwood/systemctl-tui/releases/download/{{ release.tag }}/systemctl-tui-x86_64-unknown-linux-musl.tar.gz
    mode: a+x
  become: true
