- name: CAdvisor | Start container
  community.docker.docker_container:
    name: cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.50.0
    state: started
    restart_policy: unless-stopped
    labels:
      traefik.enable: 'false'
    networks:
      - name: monitoring
    command:
      --logtostderr
      --docker_only
      --store_container_labels=false
    volumes:
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg:/dev/kmsg
