- name: CAdvisor | Start container
  community.docker.docker_container:
    name: cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    state: started
    restart_policy: unless-stopped
    command: --docker_only=true
    labels:
      traefik.enable: 'false'
    networks:
      - name: monitoring
    volumes:
      - /var/lib/docker/:/var/lib/docker:ro
