- name: Download RPM
  ansible.builtin.get_url:
    url: https://app.warp.dev/download?package=rpm
    dest: "{{ setup_dir }}/warp.rpm"
    mode: "0644"

- name: Install
  ansible.builtin.dnf:
    name: "{{ setup_dir }}/warp.rpm"
    disable_gpg_check: true
    state: present
  become: true
