version: '3'

tasks:
  default:
    cmds:
      - task -l

  dev:
    desc: Setup development environment
    cmds:
      - python3 -m venv .venv && source .venv/bin/activate
      - pip install -r requirements.txt
      - task galaxy

  galaxy:
    desc: Install Ansible Galaxy roles
    cmds:
      - ansible-galaxy install -p .ansible_galaxy/roles -r requirements.yml
      - ansible-galaxy collection install -p .ansible_galaxy/collections -r requirements.yml

  lint:
    desc: Runs Ansible Lint agains manifests
    cmds:
      - ansible-lint playbooks/setup.yml roles

  check:
    desc: Check syntax of playbooks
    cmds:
      - ansible-playbook --syntax-check playbooks/*.yml

  run:
    desc: Run main playbook
    cmds:
      - ansible-playbook --ask-become-pass

  run-tag:
    desc: Run main playbook with tag
    cmds:
      - ansible-playbook --ask-become-pass --tags {{ .TAG }} playbooks/setup.yml
    preconditions:
      - test -n "${TAG}"
    vars:
      TAG: ${TAG}

