version: '3'

vars:
  playbook_name: setup.yml

tasks:
  default:
    cmds:
      - task -l

  galaxy:
    desc: Install Ansible Galaxy roles
    cmds:
      - ansible-galaxy install -r requirements.yml

  lint:
    desc: Runs Ansible Lint againt manifests
    dir: provision
    cmds:
      - ansible-lint setup.yml roles

  setup:
    desc: Setup development environment
    dir: provision
    cmds:
      - pip install -r requirements.txt
      - ansible-galaxy install -r requirements.yml
      - ansible-playbook setup.yml --ask-become-pass -i hosts

  run:
    desc: Run main playbook
    dir: provision
    cmds:
      - ansible-playbook {{ .playbook_name }} --ask-become-pass -i hosts -v

  run-tag:
    desc: Run main playbook with tag
    dir: provision
    cmds:
      - ansible-playbook {{ .playbook_name }} --ask-become-pass -i hosts --tags {{ .TAG }}
    preconditions:
      - test -n "${TAG}"
    vars:
      TAG: ${TAG}

  update-system:
    desc: Update system
    dir: provision
    cmds:
      - ansible-playbook update-system.yml --ask-become-pass -i hosts -v

  update-github:
    desc: Update all software installed from GitHub
    dir: provision
    cmds:
      - ansible-playbook {{ .playbook_name }} --ask-become-pass -i hosts -v --tags "github"
