- name: Google Cloud SDK | Add Repository
  yum_repository:
    name: google-cloud-sdk
    description: Google Cloud SDK
    baseurl: https://packages.cloud.google.com/yum/repos/cloud-sdk-el7-x86_64
    gpgkey:
      - https://packages.cloud.google.com/yum/doc/yum-key.gpg
      - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    enabled: true
    gpgcheck: true
  become: true

- name: Google Cloud SDK | Install
  dnf:
    name: google-cloud-sdk
  become: true
