- name: Kubectl | Add Repository
  ansible.builtin.yum_repository:
    baseurl: https://pkgs.k8s.io/core:/stable:/v1.28/rpm/
    description: Kubernetes
    enabled: true
    gpgcheck: true
    gpgkey: https://pkgs.k8s.io/core:/stable:/v1.28/rpm/repodata/repomd.xml.key
    name: kubernetes
    repo_gpgcheck: true
  become: true

- name: Kubectl | Install
  ansible.builtin.dnf:
    name: kubectl
    state: latest
  become: true
- name: Kubectl | Install autocomplete
  ansible.builtin.shell: kubectl completion zsh > {{ shell_completions_dir }}/_kubectl
