- name: Install networking tools
  dnf:
    name:
      - net-tools
      - traceroute
      - whois
      - nmap
      - iftop
      - tcpdump
    state: present
  become: true
  tags: ["networking"]

- import_tasks: firewall.yml
  tags: ["networking", "firewall"]
- import_tasks: speedtest-cli.yml
  tags: ["networking", "speedtest"]
- import_tasks: dnsmasq.yml
  tags: ["networking", "dns"]
