- name: Cacher | Download AppImage
  get_url:
    url: "https://s3.amazonaws.com/download.cacher.io/Cacher-2.23.0.AppImage"
    dest: "/opt/Cacher.AppImage"
    mode: a+x
  become: true

- name: Cacher | Install Desktop file
  template:
    src: applications/cacher.desktop
    dest: "{{ applications_dir }}/cacher.desktop"
