- name: Pulumi | Get latest release
  github_release:
    user: pulumi
    repo: pulumi
    action: latest_release
  register: release

- debug:
    var: release

- name: Pulumi | Ensure bin dir exists
  file:
    path: "{{ ansible_env.HOME}}/.pulumi/bin"
    state: directory

- name: Pulimi | Install
  unarchive:
    src: https://get.pulumi.com/releases/sdk/pulumi-{{ release.tag }}-linux-x64.tar.gz
    remote_src: true
    extra_opts: [--strip-components=1]
    mode: a+x
    dest: "{{ ansible_env.HOME}}/.pulumi/bin"
