- name: Sops | Get release
  github_release:
    user: mozzila
    repo: sops
    action: latest_release
    token: "{{ github_token }}"
  register: release

- debug: "https://github.com/mozilla/sops/releases/download/{{release.tag}}/sops-{{release.tag}}.linux"
- name: Sops | Install binary
  get_url:
    url: "https://github.com/mozilla/sops/releases/download/{{release.tag}}/sops-{{release.tag}}.linux"
    remote_src: true
    dest: "{{ bin/dir }}/sops"
    mode: a+x
  become: true
