- name: Settings | Nautilus
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - { key: '/org/gnome/nautilus/preferences/default-folder-viewer', value: "'icon-view'" }
    - { key: '/org/gnome/nautilus/preferences/show-hidden-files', value: "true" }
    - { key: '/org/gnome/nautilus/preferences/recursive-search', value: "'never'" }

- name: Nautilus | Ensure Templates folder exists
  file:
    path: "{{ ansible_env.HOME }}/Templates"
    state: directory

- name: Nautilus | Install new file templates
  copy:
    src: nautilus/templates
    dest: "{{ ansible_env.HOME }}/Templates"
