- name: Get latest release
  community.general.github_release:
    action: latest_release
    repo: rclone
    token: '{{ github_token }}'
    user: rclone
  register: release

- name: Extract archive
  ansible.builtin.unarchive:
    src: "https://github.com/rclone/rclone/releases/download/{{ release.tag }}/rclone-{{ release.tag }}-linux-amd64.zip"
    dest: "{{ setup_dir }}"
    remote_src: true
    mode: "0755"

- name: Install rclone
  ansible.builtin.copy:
    src: "{{ setup_dir }}/rclone-{{ release.tag }}-linux-amd64"
    dest: "/usr/local/bin/rclone"
    mode: "a+x"
  become: true
