- name: Get latest release
  community.general.github_release:
    action: latest_release
    user: bensadeh
    repo: tailspin
    token: "{{ github_token }}"
  register: release

- name: Download and Install
  ansible.builtin.unarchive:
    src: https://github.com/bensadeh/tailspin/releases/download/{{ release.tag }}/tailspin-x86_64-unknown-linux-musl.tar.gz
    dest: "{{ bin_dir }}"
    mode: a+x
    remote_src: true
  become: true
