- name: Installs yadm
  dnf:
    name: https://download.opensuse.org/repositories/home:/TheLocehiliosan:/yadm/Fedora_31/noarch/yadm-2.4.0-65.1.noarch.rpm
    state: present
  become: true

- name: Dotfiles | Clone Repository
  command: yadm clone "{{ dotfiles_repo_url }} -f"
  args:
    creates: "{{ ansible_env.HOME }}/.config/.yadm"

- name: Dotfiles | Decrypt
  command: yadm decrypt

- name: Dotfiles | Update remote url to ssh
  command: yadm remote set-url origin "{{ dotfiles_ssh_repo_url }}"

- name: Dotfiles | Fix netrc permissions
  file:
    path: "{{ ansible_env.HOME }}/.netrc"
    mode: "0600"
  become: true
