- name: Get the version of cargo
  ansible.builtin.command:
    cmd: cargo --version
  register: cargo_version
  ignore_errors: true

- name: Fail if cargo is not installed
  ansible.builtin.fail:
    msg: "cargo is not installed"
  when: cargo_version.rc != 0

- name: Install netscanner
  ansible.builtin.command:
    cmd: cargo install netscanner
  args:
    creates: /{{ ansible_env.HOME }}/.cargo/bin/netscanner
