- name: Kubeseal | Get latest release
  github_release:
    user: bitnami-labs
    repo: sealed-secrets
    action: latest_release
    token: "{{ github_token }}"
  register: kubeseal_release

- name: Kail | Download Archive
  unarchive:
    src: "https://github.com/bitnami-labs/sealed-secrets/releases/download/{{ kubeseal_release.tag }}/kubeseal-linux-amd64"
    remote_src: true
    dest: "{{ setup_dir }}"

- name: Kail Install
  copy:
    src: "{{ setup_dir }}/kail"
    dest: "{{ bin_dir }}"
    mode: a+x
  become: true
