- name: Kind | Get Latest release
  github_release:
    user: kubernetes-sigs
    repo: kind
    action: latest_release
    token: "{{ github_token }}"
  register: kind_release

- name: Kind | Download and install
  get_url:
    url: "https://github.com/kubernetes-sigs/kind/releases/download/{{ kind_release.tag }}/kind-linux-amd64"
    mode: a+x
    dest: "{{ bin_dir }}/kind"
  become: true
