- name: Kubectx | Get latest release
  github_release:
    user: ahmetb
    repo: kubectx
    action: latest_release
  register: kubectx_release

- name: Kubectx | Create tmp dir
  file:
    path: "{{ setup_dir }}/kubectx"
    state: directory
    mode: 0755

- name: Kubectx | Download tarball
  unarchive:
    src: https://github.com/ahmetb/kubectx/archive/{{ kubectx_release.tag }}.tar.gz
    remote_src: true
    extra_opts: [--strip-components=1]
    dest: "{{ setup_dir }}/kubectx"

- name: Kubectx | Install
  copy:
    src: "{{ setup_dir }}/kubectx/kubectx"
    dest: "{{ bin_dir }}/kubectx"
    mode: a+x
  become: true

- name: Kubectx | Install Kubens
  copy:
    src: "{{ setup_dir }}/kubectx/kubens"
    dest: "{{ bin_dir }}/kubens"
    mode: a+x
  become: true
