- name: Kubeval | Get latest release
  github_release:
    user: instrumenta
    repo: kubeval
    action: latest_release
    token: "{{ github_token }}"
  register: release

- name: Kubeval | Download Archive
  unarchive:
    src: "https://github.com/instrumenta/kubeval/releases/download/{{release.tag}}/kubeval-linux-amd64.tar.gz"
    remote_src: true
    dest: "{{ setup_dir }}"
  become: true

- name: "dive | install"
  copy:
    src: "{{ setup_dir }}/kubeval"
    dest: "{{ bin_dir }}/kubeval"
    mode: "a+x"
  become: true
