- name: Get Latest release from GitHub
  community.general.github_release:
    action: latest_release
    user: sxyazi
    repo: yazi
    token: "{{ github_token }}"
  register: release

- name: Download and Install
  ansible.builtin.unarchive:
    dest: "{{ setup_dir }}"
    remote_src: yes
    src: https://github.com/sxyazi/yazi/releases/download/{{ release.tag }}/yazi-x86_64-unknown-linux-gnu.zip

- name: Copy to bin
  ansible.builtin.copy:
    src: "{{ setup_dir }}/yazi-x86_64-unknown-linux-gnu/{{ item }}"
    dest: "{{ bin_dir }}/{{ item }}"
    mode: a+x
  loop:
    - yazi
    - ya
  become: true


