- name: Install PostgresSQL client
  ansible.builtin.dnf:
    name: libpq-devel
    state: present
  become: true

- name: Install MySQL client
  ansible.builtin.dnf:
    name: community-mysql
    state: present
  become: true

- name: RBDMS cli tools
  ansible.builtin.dnf:
    name:
      - pgcli
      - mycli
    state: present
  become: true

- name: LazySQL | Get latest release
  community.general.github_release:
    action: latest_release
    user: jorgerojas26
    repo: lazysql
    token: '{{ github_token }}'
  register: lazysql_release

- name: LazySQL | Download and extract
  ansible.builtin.unarchive:
    dest: '{{ setup_dir }}'
    remote_src: true
    src: https://github.com/jorgerojas26/lazysql/releases/download/{{ lazysql_release.tag }}/lazysql_Linux_x86_64.tar.gz
  become: true

- name: LazySQL | install
  ansible.builtin.copy:
    dest: '{{ bin_dir }}/lazysql'
    mode: a+x
    src: '{{ setup_dir }}/lazysql'
  become: true
