- name: Gnome Extensions
  include_role:
    name: ansible-gnome-extensions
  vars:
    gnome_extension_ids:
      - 97
      - 906
      - 800
      - 779
      - 615
      - 517
      - 355
      - 2594
      - 2224
      - 16
      - 1544
      - 1460
      - 1379
      - 1319
      - 1162
      - 1160
      - 1007

- name: Gnome Extensions | Configure clipboard indicator
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - {
        key: "/org/gnome/shell/extensions/clipboard-indicator/history-size",
        value: 20,
      }
    - {
        key: "/org/gnome/shell/extensions/clipboard-indicator/notify-on-copy",
        value: "false",
      }

- name: Gnome Extensions | Configure Dash to Dock
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - {
        key: "/org/gnome/shell/extensions/dash-to-dock/apply-custom-theme",
        value: "false",
      }
    - {
        key: "/org/gnome/shell/extensions/dash-to-dock/background-color",
        value: "'#ffffff'",
      }
    - {
        key: "/org/gnome/shell/extensions/dash-to-dock/background-opacity",
        value: 0.0,
      }
    - {
        key: "/org/gnome/shell/extensions/dash-to-dock/dock-position",
        value: "'BOTTOM'",
      }
    - {
        key: "/org/gnome/shell/extensions/dash-to-dock/multi-monitor",
        value: "true",
      }
    - {
        key: "/org/gnome/shell/extensions/dash-to-dock/extend-height",
        value: "false",
      }
    - {
        key: "/org/gnome/shell/extensions/dash-to-dock/transparency-mode",
        value: "'FIXED'",
      }
    - {
        key: "/org/gnome/shell/extensions/dash-to-dock/hot-keys",
        value: "false",
      }
    - {
        key: "/org/gnome/shell/extensions/dash-to-dock/show-trash",
        value: "false",
      }
    - {
        key: "/org/gnome/shell/extensions/dash-to-dock/show-mounts",
        value: "false",
      }

- name: Gnome Extensions | Configure notifications alert
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - {
        key: "/org/gnome/shell/extensions/notifications-alert/color",
        value: "'#feb03e'",
      }

- name: Gnome Extensions | Configure Vitals
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - {
        key: "/org/gnome/shell/extensions/vitals/hot-sensors",
        value: ["_memory_usage_", "_system_load_1m_"],
      }
    - { key: "/org/gnome/shell/extensions/vitals/position-in-panel", value: 1 }
    - { key: "/org/gnome/shell/extensions/vitals/show-battery", value: "false" }
    - { key: "/org/gnome/shell/extensions/vitals/show-fan", value: "false" }
    - { key: "/org/gnome/shell/extensions/vitals/show-voltage", value: "false" }

- name: Gnome Extensions | Configure TimeApp
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - {
        key: "/org/gnome/shell/extensions/timepp/alarms-separate-menu",
        value: "true",
      }
    - { key: "/org/gnome/shell/extensions/timepp/unicon-mode", value: "true" }
    # - { key: '/org/gnome/shell/extensions/timepp/sections', value: "{'Timer': {'enabled': false}, 'Stopwatch': {'enabled': false}, 'Pomodoro': {'enabled': false}, 'Alarms': {'enabled': true}, 'Todo': {'enabled': true}} }"

- name: Gnome Extensions | Configure Emoji Selector
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - {
        key: "/org/gnome/shell/extensions/emoji-selector/use-keybinding",
        value: "false",
      }

- name: Gnome Extensions | Configure Auto Move Windows
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - {
        key: "/org/gnome/shell/extensions/auto-move-windows/application-list",
        value: "['firefox.desktop:1','chrome.desktop:1','code.desktop:2']",
      }
# - name: Install Pop shell
#   dnf:
#     name: "{{ item }}"
#     state: present
#   with_items:
#     - gnome-shell-extension-pop-shell
#     - gnome-shell-extension-pop-shell-shortcut-overrides
#   become: true

- name: Gnome Extensions | Configure Dash to Panel
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - {
        key: "/org/gnome/shell/extensions/dash-to-panel/dot-position",
        value: "'BOTTOM'",
      }
