- include: dropbox.yml
- include: google-chrome.yml
- include: skype.yml
- include: slack.yml
- include: discord.yml
- include: reminna.yml
- include: wireshark.yml
- include: transmission.yml
- include: uget.yml
- include: zoom.yml
- include: whatip.yml
- include: markets.yml
- include: webcatalog.yml
  tags: ["webcatalog"]
- include: whatsapp-desktop.yml
  tags: ["whatsapp", "flatpak"]
- include: edge.yml
  tags: ["edge", "browsers"]
- include: brave-browser.yml
  tags: ["brave", "browsers"]
- include: geary.yml
  tags: ["geary", "email", "flatpak"]
