- name: Install required virtualization packages
  dnf:
    name:
      - bridge-utils
      - libvirt
      - virt-install
      - qemu-kvm
      - virt-top
      - libguestfs-tools
      - virt-manager
    state: present
  become: true

- name: Run libvirt as non-root user
  lineinfile:
    path: /etc/libvirt/qemu.conf
    regexp: "^SELINUX="
    line: SELINUX=enforcing
  become: true

- name: Enable libvirtd service
  systemd:
    name: libvirtd
    state: started
    enabled: yes
  become: true
