- name: Tilix | Install package
  ansible.builtin.dnf:
    name: tilix
    state: present
  become: true

- name: Tilix | Settings
  community.general.dconf:
    key: '{{ item.key }}'
    state: present
    value: '{{ item.value }}'
  with_items:
    - key: /com/gexperts/Tilix/enable-transparency
      value: 'true'
    - key: /com/gexperts/Tilix/new-window
      value: '''new-session'''
    - key: /com/gexperts/Tilix/paste-strip-first-char
      value: 'true'
    - key: /com/gexperts/Tilix/sidebar-on-right
      value: 'true'
    - key: /com/gexperts/Tilix/theme-variant
      value: '''dark'''
    - key: /com/gexperts/Tilix/unsafe-paste-alert
      value: 'false'
    - key: /com/gexperts/Tilix/use-tabs
      value: 'true'
