- name: Install Gnome themes
  ansible.builtin.dnf:
    name:
      - papirus-icon-theme
    state: present
  become: true

- name: Enable Papirus icon theme
  community.general.dconf.dconf:
    key: /org/gnome/desktop/interface/icon-theme
    value: "'Papirus'"
