- name: Add repository
  ansible.builtin.yum_repository:
    baseurl: https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    description: Tailscale Repository
    name: tailscale
  become: true

- name: Install
  ansible.builtin.dnf:
    name: tailscale
    state: present
  become: true
