- name: Docker | Install Repo
  yum_repository:
    name: docker
    description: Docker
    baseurl: https://download.docker.com/linux/fedora/docker-ce.repo
    gpgkey: https://download.docker.com/linux/fedora/gpg

- name: Docker | Install Packages
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
  become: true

- name: Docker | Add current user to Docker group
  user:
    name: "{{ user }}"
    groups: docker
    append: yes
  become: true

# Not needed for Fedora 35
# - name: Configure Firewall
#   command: firewall-cmd --permanent --zone=trusted --add-interface=docker0 && firewall-cmd --permanent --zone=FedoraWorkstation --add-masquerade
#   become: true

- name: Docker | Start service
  systemd:
    name: docker
    state: started
    enabled: yes
  become: true

- name: Docker | Copy Daemon.json
  copy:
    src: docker/daemon.json
    dest: /etc/docker/daemon.json
  become: true
