- name: Docker | Add Docker repository
  command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
  args:
    warn: false
    creates: /etc/yum.repos/docker-ce.repo
  become: true

- name: Docker | Force to use Fedora 31 repo
  shell: sed -i 's/$releasever/31/g' /etc/yum.repos.d/docker-ce.repo
  become: true

- name: Docker | Install Packages
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  become: true

- name: Docker | Add current user to Docker group
  user:
    name: "{{ user }}"
    groups: docker
    append: yes
  become: true

- name: Configure Firewall
  command: firewall-cmd --permanent --zone=trusted --add-interface=docker0 && firewall-cmd --permanent --zone=FedoraWorkstation --add-masquerade
  become: true

- name: Docker | Start service
  systemd:
    name: docker
    state: started
    enabled: yes
  become: true

- name: Docker | Check Loki driver plugin is installed
  command: docker plugin ls
  register: docker_plugins

- name: Dcoker | Install docker plugin
  command: docker plugin install grafana/loki-docker-driver:2.2.1 --alias loki --grant-all-permissions
  when: "'Loki Logging Driver' not in docker_plugins.stdout"
  notify: restart docker

- name: Docker | Copy Daemon.json
  copy:
    src: docker/daemon.json
    dest: /etc/docker/daemon.json
  become: true
