- name: lazydocker | Get latest release
  github_release:
    user: jesseduffield
    repo: lazydocker
    action: latest_release
  register: release

- name: "lazydocker | Download"
  unarchive:
    src: "https://github.com/jesseduffield/lazydocker/releases/download/{{ release.tag }}/lazydocker_{{ release.tag[1:] }}_Linux_x86_64.tar.gz"
    remote_src: true
    dest: "{{ setup_dir }}"
  become: true

- name: "lazydocker | Install"
  copy:
    src: "{{ setup_dir }}/lazydocker"
    dest: "{{ bin_dir }}/lazydocker"
    mode: a+x
  become: true
