- name: Docker | Create Portainer volume
  docker_volume:
    name:  portainer_data
    state: present
  become: true

- name: Docker | Start Portainer container
  docker_container:
    name: portainer
    image: portainer/portainer
    state: started
    ports:
      - "9000:9000"
    restart_policy: "always"
    volumes:
      - "portainer_data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
  become: true
