- name: Install firewalld
  ansible.builtin.dnf:
    name: firewalld
    state: present
  become: true

- name: Enable and start firewalld
  ansible.builtin.systemd:
    name: firewalld
    enabled: true
    state: started
  become: true

- name: Enable masquerading in firewalld
  ansible.posix.firewalld:
    zone: public
    masquerade: true
    permanent: true
    state: enabled
  become: true

#"- name: Allow access from Docker network to the host
#  ansible.posix.firewalld:
#    zone: public
#    rich_rule: "source address=172.17.0.1/24"
#    permanent: true
#    state: enabled
#  become: true

- name: Install Firewalld config GUI
  ansible.builtin.dnf:
    name: firewall-config
    state: present
  become: true
