- name: Allow sudo without re entering the passowrd
  ansible.builtin.lineinfile:
    line: '%%wheel  ALL=(ALL) NOPASSWD: ALL'
    path: /etc/sudoers
    regexp: '^# %wheel  ALL=(ALL) NOPASSWD: ALL'
    state: present
    validate: /usr/sbin/visudo -cf %s
  become: true
