- name: Check nas_ip is defined
  ansible.builtin.fail:
    msg: "nas_ip is not defined"
  when: nas_ip is not defined

- name: Ensure mount points exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: "{{ user }}"
    group: "{{ user }}"
  loop:
    - /mnt/nas-media
    - /mnt/nas-backup
  become: true

- name: Mount NAS media share
  ansible.posix.mount:
    path: /mnt/nas
    src: "{{ nas_ip }}:/media"
    fstype: nfs
    state: present
    opts: "{{ mounts_nfs_default_opts }}"
  become: true

- name: Mount NAS backups share
  ansible.posix.mount:
    path: /mnt/nas
    src: "{{ nas_ip }}:/backups"
    fstype: nfs
    state: present
    opts: "{{ mounts_nfs_default_opts }}"
  become: true
