- name: Import the Microsoft GPG key
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc
  become: true

- name: Add the Microsoft Edge repository
  ansible.builtin.yum_repository:
    name: microsoft-edge
    description: Microsoft Edge Browser
    baseurl: https://packages.microsoft.com/yumrepos/edge
    gpgcheck: true
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    enabled: true
  become: true

- name: Install Microsoft Edge stable version
  ansible.builtin.dnf:
    name: microsoft-edge-stable
  become: true
