- name: Fluxctl | Get latest release
  github_release:
    user: FiloSottile
    repo: mkcert
    action: latest_release
    token: "{{ github_token }}"
  register: release

- name: Fluxctl | Install Binary
  get_url:
    url: "https://github.com/fluxcd/flux/releases/download/1.19.0/fluxctl_linux_amd64"
    dest: "{{ bin_dir }}/fluxctl"
    mode: a+x
  become: true
