- name: Install required virtualization packages
  dnf:
    name:
      - bridge-utils
      - libvirt
      - virt-install
      - qemu-kvm
      - virt-top
      - libguestfs-tools
      - virt-manager
    state: present

- name: Enable libvirtd service
  systemd:
    name: libvirtd
    state: started
    enabled: yes
