- name: Installs NodeJS
  dnf:
    name: nodejs
    state: present
  become: true

- name: Installs Global NPM Packages
  npm:
    name: "{{ item }}"
    global: yes
  with_items:
    - "@gridsome/cli"
    - "semantic-release"
    - "@semantic-release/changelog"
    - "@semantic-release/git"
    - "@vue/cli"
    - "artillery"
    - "caniuse-cmd"
    - "commitizen"
    - "conduct"
    - "conventional-changelog-cli"
    - "create-nuxt-app"
    - "create-react-app"
    - "electron"
    - "eslint"
    - "fkill-cli"
    - "gatsby-cli"
    - "localtunnel"
    - "nativefier"
    - "nativescript"
    - "mklicense"
    - "netlify-cli"
    - "pageres-cli"
    - "sao"
    - "serve"
    - "serverless"
    - "svg-term-cli"
    - "trash-cli"
    - "vuepress"
    - "weallcontribute"
    - "yo"
    - "yarn"
    - "mdless"
    - "readme-md-generator"
    - "add-gitignore"
    - "carbon-now-cli"
    - "sitespeed.io"
    - "mermaid.cli"
    - "cloudinary-cli"
    - "svg-term-cli"
    - "typescript"
    - "fx"
    - "@cacherapp/cli@"
    - "fast-cli"
    - "@nestjs/cli"
    - "tablemark-cli"
