- name: Teleconsole | Get latest release
  github_release:
    user: gravitational
    repo: teleconsole
    action: latest_release
    token: "{{ github_token }}"
  register: release

- name: Teleconsole | Install
  unarchive:
    src: "https://github.com/gravitational/teleconsole/releases/download/{{ release.tag }}/teleconsole-v{{ release.tag }}-linux-amd64.tar.gz"
    remote_src: true
    dest: "{{ bin_dir }}"
  become: true
