- name: Node | Install
  ansible.builtin.dnf:
    name: nodejs
    state: present
  become: true

- name: FNM | Get latest release version
  community.general.github_release:
    action: latest_release
    repo: fnm
    token: '{{ github_token }}'
    user: Schniz
  register: fnm_release

- name: FNM | Install
  ansible.builtin.unarchive:
    dest: '{{ bin_dir }}'
    mode: a+x
    remote_src: true
    src: https://github.com/Schniz/fnm/releases/download/{{ fnm_release.tag }}/fnm-linux.zip
  become: true

- name: Install Global NPM packages
  community.general.npm:
    global: true
    name: '{{ item }}'
  with_items:
    - pnpm
    - commitizen
    - conduct
    - pageres-cli
    - readme-md-generator
    - serve
    - svgo
    - sharp-cli
    - plop
    - typescript
