# Configure Traefik to use TLS
# See: https://doc.traefik.io/traefik/https/tls/#certificates-definition
tls:
  stores:
    default: {}
  certificates:
     - certFile: /etc/certs/traefik.localhost.pem
       keyFile: /etc/certs/traefik.localhost-key.pem
     - certFile: /etc/certs/grafana.localhost.pem
       keyFile: /etc/certs/grafana.localhost-key.pem
     - certfile: /etc/certs/sourcegraph.localhost.pem
       keyfile: /etc/certs/sourcegraph.localhost-key.pem
     - certFile: /etc/certs/grafana.localhost.pem
       keyFile: /etc/certs/grafana.localhost-key.pem
     - certFile: /etc/certs/portainer.localhost.pem
       keyFile: /etc/certs/portainer.localhost-key.pem
     - certFile: /etc/certs/prometheus.localhost.pem
       keyFile: /etc/certs/prometheus.localhost-key.pem
