- name: Install
  ansible.builtin.dnf:
    name: asciinema
    state: present
  become: true

- name: Agg | Get latest release
  community.general.github_release:
    action: latest_release
    user: asciinema
    repo: agg
    token: '{{ github_token }}'
  register: release

- name: Agg | Download and Install
  ansible.builtin.get_url:
    dest: '{{ bin_dir }}/agg'
    force: true
    mode: a+x
    url: https://github.com/asciinema/agg/releases/download/{{ release.tag }}/agg-x86_64-unknown-linux-gnu
  become: true
