- name: Lefthook | Get Latest release
  community.general.github_release:
    action: latest_release
    repo: lefthook
    token: '{{ github_token }}'
    user: evilmartians
  register: lefthook_release

- name: Lefthook | Install
  ansible.builtin.dnf:
    disable_gpg_check: true
    name: https://github.com/evilmartians/lefthook/releases/download/{{ lefthook_release.tag }}/lefthook_{{ lefthook_release.tag[1:] }}_amd64.rpm
    state: present
  become: true
