- include: bleachbit.yml
  tags: ["bleachbit", "utilities"]
- include: cryptomator.yml
  tags: ["cryptomator", "utilities"]
- include: menulibre.yml
  tags: ["menulibre", "utilities"]
- include: stacer.yml
  tags: ["stacer", "utilities"]
- include: tilix.yml
  tags: ["tilix", "utilities"]
- include: ulauncher.yml
  tags: ["ulauncher", "utilities"]
- include: weather.yml
  tags: ["weather", "utilities"]
- include: restic.yml
  tags: ["restic", "utilities"]
- include: grsync.yml
  tags: ["grsync", "utilities"]
- include: authy.yml
  tags: ["authy"]
- include: obfuscate.yml
  tags: ["obfuscate"]
- include: timeshift.yml
  tags: ["utilities"]
- include: mediawriter.yml
  tags: ["mediawriter"]
- include: text-snatcher.yml
  tags: ["text-snatcher"]
