- import_tasks: bleachbit.yml
  tags: ["bleachbit", "utilities"]
- import_tasks: cryptomator.yml
  tags: ["cryptomator", "utilities"]
- import_tasks: menulibre.yml
  tags: ["menulibre", "utilities"]
- import_tasks: stacer.yml
  tags: ["stacer", "utilities"]
- import_tasks: tilix.yml
  tags: ["tilix", "utilities"]
- import_tasks: ulauncher.yml
  tags: ["ulauncher", "utilities"]
- import_tasks: weather.yml
  tags: ["weather", "utilities"]
- import_tasks: restic.yml
  tags: ["restic", "utilities"]
- import_tasks: grsync.yml
  tags: ["grsync", "utilities"]
- import_tasks: authy.yml
  tags: ["authy"]
- import_tasks: obfuscate.yml
  tags: ["obfuscate"]
- import_tasks: timeshift.yml
  tags: ["utilities"]
- import_tasks: mediawriter.yml
  tags: ["mediawriter"]
- import_tasks: text-snatcher.yml
  tags: ["text-snatcher"]
- import_tasks: text-editor.yml
  tags: ["text-editor"]
- import_tasks: solaar.yml
  tags: ["solaar"]
- import_tasks: deskcreen.yml
  tags: ["deskscreen"]
- import_tasks: smile.yml
  tags: ["flatpak"]
- import_tasks: blanket.yml
  tags: ["flatpak"]
- import_tasks: nap.yml
  tags: ["nap"]
