- name: Etcher | Get latest release version
  github_release:
    user: balena-io
    repo: etcher
    action: latest_release
    token: "{{ github_token }}"
  register: etcher_release

- name: Etcher | Install
  dnf:
    name: https://github.com/balena-io/etcher/releases/download/{{etcher_release.tag}}/balena-etcher-electron-{{ etcher_release.tag[1:]}}.x86_64.rpm
    state: present
    disable_gpg_check: true
  become: true
