- include: bleachbit.yml
  tags: ["bleachbit", "utilities"]
- include: cryptomator.yml
  tags: ["cryptomator", "utilities"]
- include: etcher.yml
  tags: ["etcher", "utilities"]
- include: menulibre.yml
  tags: ["menulibre", "utilities"]
- include: stacer.yml
  tags: ["stacer", "utilities"]
- include: tilix.yml
  tags: ["tilix", "utilities"]
- include: ulauncher.yml
  tags: ["ulauncher", "utilities"]
- include: weather.yml
  tags: ["weather", "utilities"]
- include: restic.yml
  tags: ["restic", "utilities"]
- include: grsync.yml
  tags: ["grsync", "utilities"]
