- name: Nap | Get latest release version
  github_release:
    user: maaslalani
    repo: nap
    action: latest_release
    token: "{{ github_token }}"
  register: nap_release

- name: Nap | Download
  unarchive:
    remote_src: true
    src: https://github.com/maaslalani/nap/releases/download/{{ nap_release.tag }}/nap_{{ nap_release.tag[1:] }}_linux_amd64.tar.gz
    dest: "{{ setup_dir }}"
  become: true

- name: Nap | install
  copy:
    src: "{{ setup_dir }}/nap"
    dest: "{{ bin_dir }}"
    mode: "a+x"
  become: true
