# =======================
# Languages and runtimes
# =======================
- include: python.yml
  tags: ["python"]
- include: ruby.yml
  tags: ["ruby"]
- include: php.yml
  tags: ["php"]
- include: node.yml
  tags: ["node"]
- include: golang.yml
  tags: ["golang"]
- include: java.yml
  tags: ["java"]
- include: rust.yml
  tags: ["rust"]

# =======================
# Tools
# =======================
- include: vim.yml
  tags: ["vim"]
- include: vscode.yml
  tags: ["vscode"]
- include: postman.yml
  tags: ["postman"]
- include: meld.yml
  tags: ["meld"]
- include: gitkraken.yml
  tags: ["gitkraken"]
- include: regex-tester.yml
  tags: ["regex-tester"]
- include: dbeaver.yml
  tags: ["dbeaver"]
- include: hugo.yml
  tags: ["hugo"]
- include: jetbrains-toolbox.yml
  tags: ["jetbrains"]

# ===================
# Docker
# ===================
- include: docker/docker.yml
  tags: ["docker"]
- include: docker/ctop.yml
  tags: ["docker", "ctop", "github"]
- include: docker/lazydocker.yml
  tags: ["docker", "lazydocker", "github"]
- include: docker/dive.yml
  tags: ["docker", "dive", "github"]
- include: sops.yml
  tags: ["sops", "github"]

- include: docker/containers/traefik.yml
  tags: ["docker", "traefik", "docker-app"]
- include: docker/containers/portainer.yml
  tags: ["docker", "portainer", "docker-app"]
- include: docker/containers/grafana.yml
  tags: ["docker", "grafana", "docker-app"]
- include: docker/containers/devdns.yml
  tags: ["docker", "grafana", "docker-app"]

# # ============================
# # Kubernetes
# # ============================
- include: kubernetes/minikube.yml
  tags: ["minikube"]
- include: kubernetes/kubectl.yml
  tags: ["kubernetes", "kubectl"]
- include: kubernetes/kubectx.yml
  tags: ["kubernetes", "kubectx", "github"]
- include: kubernetes/helm.yml
  tags: ["kubernetes", "helm"]
- include: kubernetes/kail.yml
  tags: ["kubernetes", "kail", "github"]
- include: kubernetes/kubeval.yml
  tags: ["kubernetes", "kubeval", "github"]
- include: kubernetes/k9s.yml
  tags: ["kubernetes", "k9s", "github"]
- include: kubernetes/kind.yml
  tags: ["kubernetes", "kind", "github"]
- include: kubernetes/lens.yml
  tags: ["kubernetes", "lens"]

# ===================
# Cloud tools
# ===================
- include: cloud/awscli.yml
  tags: ["awscli"]
- include: cloud/doctl.yml
  tags: ["doctl", "github"]
- include: cloud/gcloud.yml
  tags: ["gcloud"]
- include: cloud/heroku.yml
  tags: ["heroku"]
- include: cloud/fly.yml
  tags: ["fly"]

# ===================
# Other
# ===================
- include: mkcert.yml
  tags: ["mkcert", "github"]
- include: dbcli.yml
- include: tldr.yml
  tags: ["tldr"]
- include: git-tools.yml
  tags: ["github"]
- include: terraform.yml
  tags: ["terraform", "github"]
- include: sqllitebrowser.yml
- include: cacher.yml
- include: pulumi.yml
  tags: ["pulumi", "github"]
- include: spotlight-studio.yml
  tags: ["spotlight-studio"]
- include: gh-cli.yml
  tags: ["gh-cli", "githhub"]
- include: flux.yml
  tags: ["fluxcd", "github"]
- include: goreleaser.yml
  tags: ["goreleaser", "github"]
- include: direnv.yml
  tags: ["direnv"]
- include: zeal.yml
  tags: ["zeal"]
- include: mage.yml
  tags: ["go", "mage"]
- include: lefthook.yml
  tags: ["go", "lefthook"]
- include: github-desktop.yml
  tags: ["github-desktop"]
- include: mongodb.yml
  tags: [mongodb]
