# =======================
# Languages and runtimes
# =======================
- import_tasks: python.yml
  tags: ["python"]
- import_tasks: ruby.yml
  tags: ["ruby"]
- import_tasks: php.yml
  tags: ["php"]
- import_tasks: node.yml
  tags: ["node"]
- import_tasks: golang.yml
  tags: ["golang"]
- import_tasks: java.yml
  tags: ["java"]
- import_tasks: rust.yml
  tags: ["rust"]

# =======================
# Tools
# =======================
- import_tasks: vim.yml
  tags: ["vim"]
- import_tasks: vscode.yml
  tags: ["vscode"]
- import_tasks: postman.yml
  tags: ["postman"]
- import_tasks: meld.yml
  tags: ["meld"]
- import_tasks: gitkraken.yml
  tags: ["gitkraken"]
- import_tasks: regex-tester.yml
  tags: ["regex-tester"]
- import_tasks: dbeaver.yml
  tags: ["dbeaver"]
- import_tasks: hugo.yml
  tags: ["hugo"]
- import_tasks: jetbrains-toolbox.yml
  tags: ["jetbrains"]

# ===================
# Docker
# ===================
- import_tasks: docker/docker.yml
  tags: ["docker"]
- import_tasks: docker/ctop.yml
  tags: ["docker", "ctop", "github"]
- import_tasks: docker/lazydocker.yml
  tags: ["docker", "lazydocker", "github"]
- import_tasks: docker/dive.yml
  tags: ["docker", "dive", "github"]
- import_tasks: sops.yml
  tags: ["sops", "github"]

- import_tasks: docker/containers/traefik.yml
  tags: ["docker", "traefik", "docker-app"]
- import_tasks: docker/containers/portainer.yml
  tags: ["docker", "portainer", "docker-app"]
- import_tasks: docker/containers/grafana.yml
  tags: ["docker", "grafana", "docker-app"]
- import_tasks: docker/containers/devdns.yml
  tags: ["docker", "grafana", "docker-app"]

# # ============================
# # Kubernetes
# # ============================
- import_tasks: kubernetes/minikube.yml
  tags: ["minikube"]
- import_tasks: kubernetes/kubectl.yml
  tags: ["kubernetes", "kubectl"]
- import_tasks: kubernetes/kubectx.yml
  tags: ["kubernetes", "kubectx", "github"]
- import_tasks: kubernetes/helm.yml
  tags: ["kubernetes", "helm"]
- import_tasks: kubernetes/kail.yml
  tags: ["kubernetes", "kail", "github"]
- import_tasks: kubernetes/kubeval.yml
  tags: ["kubernetes", "kubeval", "github"]
- import_tasks: kubernetes/k9s.yml
  tags: ["kubernetes", "k9s", "github"]
- import_tasks: kubernetes/kind.yml
  tags: ["kubernetes", "kind", "github"]
- import_tasks: kubernetes/lens.yml
  tags: ["kubernetes", "lens"]

# ===================
# Cloud tools
# ===================
- import_tasks: cloud/awscli.yml
  tags: ["awscli"]
- import_tasks: cloud/doctl.yml
  tags: ["doctl", "github"]
- import_tasks: cloud/gcloud.yml
  tags: ["gcloud"]
- import_tasks: cloud/heroku.yml
  tags: ["heroku"]
- import_tasks: cloud/fly.yml
  tags: ["fly"]

# ===================
# Other
# ===================
- import_tasks: mkcert.yml
  tags: ["mkcert", "github"]
- import_tasks: dbcli.yml
- import_tasks: tldr.yml
  tags: ["tldr"]
- import_tasks: git-tools.yml
  tags: ["github"]
- import_tasks: terraform.yml
  tags: ["terraform", "github"]
- import_tasks: sqllitebrowser.yml
- import_tasks: pulumi.yml
  tags: ["pulumi", "github"]
- import_tasks: spotlight-studio.yml
  tags: ["spotlight-studio"]
- import_tasks: gh-cli.yml
  tags: ["gh-cli", "github"]
- import_tasks: glab-cli.yml
  tags: ["glab-cli", "gitlab"]
- import_tasks: flux.yml
  tags: ["fluxcd", "github"]
- import_tasks: goreleaser.yml
  tags: ["goreleaser", "github"]
- import_tasks: direnv.yml
  tags: ["direnv"]
- import_tasks: zeal.yml
  tags: ["zeal"]
- import_tasks: mage.yml
  tags: ["go", "mage"]
- import_tasks: lefthook.yml
  tags: ["go", "lefthook"]
- import_tasks: github-desktop.yml
  tags: ["github-desktop"]
- import_tasks: mongodb.yml
  tags: [mongodb]
- import_tasks: redis.yml
  tags: [redis]
- import_tasks: fnm.yml
  tags: [fnm]
