- name: Fluxctl | Get latest release
  github_release:
    user: fluxcd
    repo: flux
    action: latest_release
    token: "{{ github_token }}"
  register: release

- name: Fluxctl | Install Binary
  get_url:
    url: "https://github.com/fluxcd/flux/releases/download/{{ release.tag }}/fluxctl_linux_amd64"
    dest: "{{ bin_dir }}/fluxctl"
    mode: a+x
  become: true
