- name: Mitmproxy | Get Latest release
  github_release:
    user: mitmproxy
    repo: mitmproxy
    action: latest_release
    token: "{{ github_token }}"
  register: mitmproxy_release

- name: Mitmproxy | Download
  unarchive:
    src: https://mitmproxy.org/downloads/#{{ mitmproxy_release.tag }} /mitmproxy-{{ mitmproxy_release.tag }}-linux.tar.gz
    remote_src: true
    dest: "{{ bin_dir }}"
  become: true
