- name: Installs NodeJS
  dnf:
    name: nodejs
    state: present
  become: true

- name: Installs Global NPM Packages
  npm:
    name: "{{ item }}"
    global: yes
  with_items:
    - "@cacherapp/cli@"
    - "@gridsome/cli"
    - "@nestjs/cli"
    - "@semantic-release/changelog"
    - "@semantic-release/git"
    - "@vue/cli"
    - "add-gitignore"
    - "artillery"
    - "caniuse-cmd"
    - "carbon-now-cli"
    - "cloudinary-cli"
    - "commitizen"
    - "conduct"
    - "conventional-changelog-cli"
    - "create-nuxt-app"
    - "create-react-app"
    - "electron"
    - "eslint"
    - "fauna-shell"
    - "fast-cli"
    - "firebase-tools"
    - "fkill-cli"
    - "fx"
    - "gatsby-cli"
    - "get-port-cli"
    - "localtunnel"
    - "hasha-cli"
    - "mdless"
    - "mermaid.cli"
    - "mklicense"
    - "nativefier"
    - "nativescript"
    - "netlify-cli"
    - "pageres-cli"
    - "readme-md-generator"
    - "sao@beta"
    - "semantic-release"
    - "serve"
    - "svgo"
    - "serverless"
    - "sitespeed.io"
    - "svg-term-cli"
    - "tablemark-cli"
    - "trash-cli"
    - "typescript"
    - "vuepress"
    - "weallcontribute"
    - "yarn"
    - "plop"
    - "vercel"
    - "@cloudflare/wrangler"

- name: FNM | Get latest release version
  github_release:
    user: bitwarden
    repo: cli
    action: latest_release
    token: "{{ github_token }}"
  register: fnm_release

- name: FNM | Install
  unarchive:
    remote_src: true
    src: https://github.com/Schniz/fnm/releases/download/{{ fnm_release.tag }}/fnm-linux.zip
    dest: "{{ bin_dir }}"
    mode: a+x
  become: true
