- name: PHP | Install
  dnf:
    name:
      - php-cli
      - php-curl
      - php-intl
      - php-pdo
      - php-mysqlnd
      - php-json
      - php-mcrypt
      - composer
  become: true

- name: Symfony CLI | Download Installer
  get_url:
    url: https://get.symfony.com/cli/installer
    dest: "{{ setup_dir }}/symfony-installer"

- name: Symfony CLI | Install
  command: "bash {{ setup_dir }}/symfony-installer"
  become: true
