- name: Python | Install PIP packages
  pip:
    name:
      - requests
      - bandit
      - flake8
      - pyflakes
      - pycodestyle
      - yapf
      - pre-commit
      - mkdocs
      - glances
      - socli
      - lorem
      - algoliasearch
      - pwgen
      - glob2
      - python-gitlab
      - docker
      - memoization
      - PyGithub
      - Cloudflare
      - ansible-lint
  become: true

- name: Python | Install system packages
  dnf:
    name: python3-ansible-lint
    state: present
  become: true
