- name: Ruby | Install
  dnf:
    name:
      - ruby
      - zlib
    state: present
  become: true

- name: Installs Global Rubygems
  gem:
    name: "{{ item }}"
  with_items:
    - rake
    - bundler
