- name: Watchexec | Get latest release
  github_release:
    user: watchexec
    repo: watchexec
    action: latest_release
    token: "{{ github_token }}"
  register: release

- name: Watchexec | Install
  dnf:
    name: https://github.com/watchexec/watchexec/releases/download/{{ release.tag }}/watchexec-{{ release.tag[1:] }}-x86_64-unknown-linux-gnu.rpm
    state: present
    disable_gpg_check: yes
  become: true
