- name: Check if nix is installed
  ansible.builtin.command: which nix
  register: nix_installed
  failed_when: nix_installed.rc != 0
  ignore_errors: true

- name: Install nix
  ansible.builtin.shell: curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install --no-confirm
  when: nix_installed.rc != 0
  become: true

- name: Ensure nixpkgs config directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/nixpkgs"
    state: directory
    mode: '0755'

- name: Configure NUR
  ansible.builtin.template:
    src: nixpkgs.config.nix.j2
    dest: "{{ ansible_env.HOME }}/.config/nixpkgs/config.nix"
    mode: '0644'

- name: Alejandra | Get latest release
  community.general.github_release:
    action: latest_release
    user: kamadorueda
    repo: alejandra
    token: "{{ github_token }}"
  register: alejandra_release

- name: Alejandra | Install
  ansible.builtin.get_url:
    url: "https://github.com/kamadorueda/alejandra/releases/download/{{ alejandra_release.tag }}-x86_64-unknown-linux-gnu"
    dest: "{{ bin_dir }}/alejandra"
    mode: a+x
  become: true
