- name: Get release
  community.general.github_release:
    action: latest_release
    repo: helm
    token: '{{ github_token }}'
    user: helm
  register: helm_release

- name: Create tmp dir
  ansible.builtin.file:
    mode: '0755'
    path: '{{ setup_dir }}/helm'
    state: directory

- name: Download Archive
  ansible.builtin.unarchive:
    dest: '{{ setup_dir }}/helm'
    remote_src: true
    src: https://get.helm.sh/helm-{{ helm_release.tag }}-linux-amd64.tar.gz

- name: Install
  ansible.builtin.copy:
    dest: '{{ bin_dir }}'
    mode: a+x
    src: '{{ setup_dir }}/helm/linux-amd64/helm'
  become: true

- name: Install autocomplete
  ansible.builtin.shell: helm completion zsh > {{ shell_completions_dir }}/_helm

