
- import_tasks: 'traefik.yml'
  tags: 'traefik'

- import_tasks: 'portainer.yml'
  tags: 'portainer'

- name: Create monitoring network
  community.docker.docker_network:
    name: monitoring
    state: present
  tags: ['docker-monitoring-stack']

- import_tasks: 'grafana.yml'
  tags: ['grafana', 'docker-monitoring-stack']

- import_tasks: 'loki.yml'
  tags: ['loki', 'docker-monitoring-stack']

- import_tasks: 'promtail.yml'
  tags: ['promtail', 'docker-monitoring-stack']

- import_tasks: 'cadvisor.yml'
  tags: ['cadvisor', 'docker-monitoring-stack']

- import_tasks: 'prometheus.yml'
  tags: ['prometheus', 'docker-monitoring-stack']

- import_tasks: 'node-exporter.yml'
  tags: ['node-exporter', 'docker-monitoring-stack']
