- name: cAdvisor | Start container
  community.docker.docker_container:
    name: cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    command: --docker_only=true
    state: started
    restart_policy: "unless-stopped"
    networks:
      - name: monitoring
      - name: traefik-public
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/kmsg:/dev/kmsg
    labels:
      traefik.enable: "true"
      traefik.http.routers.cadvisor.rule: "Host(`cadvisor.docker`)"
      traefik.http.routers.cadvisor.entrypoints: "web"
      traefik.http.services.cadvisor.loadbalancer.server.port: "8080"
      traefik.docker.network: traefik-public


