- name: Docker apps
  hosts: all
  roles:
    - { role: traefik, tags: [traefik, docker-apps] }
    - { role: cadvisor, tags: [cadvisor, docker-app] }
    - { role: grafana, tags: [grafana, docker-apps] }
    - { role: loki, tags: [loki, docker-apps] }
    - { role: node-exporter, tags: [node-exporter, docker-apps] }
    - { role: sourcegraph, tags: [sourcegraph, docker-apps] }
    - { role: prometheus, tags: [prometheus, docker-apps] }
    - { role: promtail, tags: [promtail, docker-apps] }
    - { role: portainer, tags: [portainer, docker-apps] }
    - { role: dnsdock, tags: [dnsdock, docker-apps] }
    - { role: dozzle, tags: [dozzle, docker-apps] }
