- name: Install rpmfusion repo
  ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
  loop:
      - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
      - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
  become: true
