- name: Helm | Get release
  github_release:
    user: helm
    repo: helm
    action: latest_release
    token: "{{ github_token }}"
  register: helm_release

- name: Helm | Create tmp dir
  file:
    path: "{{ setup_dir }}/helm"
    state: directory

- name: Helm | Download Archive
  unarchive:
    src: "https://get.helm.sh/helm-{{helm_release.tag}}-linux-amd64.tar.gz"
    remote_src: true
    dest: "{{ setup_dir }}/helm"

- name: Helm | Install
  copy:
    src: "{{ setup_dir }}/helm/linux-amd64/helm"
    dest: "{{ bin_dir }}"
    mode: a+x
  become: true

- name: Helm | Install helm-secrets plugin
  command: helm plugin install https://github.com/futuresimple/helm-secrets

- name: Helm | Install autocomplete
  shell: helm completion zsh > {{ shell_completions_dir }}/_helm

- name: Helm | Add stable repo
  command: helm repo add stable https://kubernetes-charts.storage.googleapis.com

- name: Helm | Add bitnani repo
  command: helm repo add bitnami https://charts.bitnami.com/bitnami

- name: Helm | Add fluxcd repo
  command: helm repo add fluxcd https://charts.fluxcd.io

- name: Helm | Update repos
  command: helm repo update
