- name: Kubernetic | Create Tmp dir
  file:
    path: "{{ setup_dir }}/kubernetic"
    state: directory

- name: Kubernetic | Download
  unarchive:
    src: https://kubernetic.s3.amazonaws.com/Kubernetic-{{kubernetic_version }}.tar.gz
    remote_src: true
    dest: "{{ setup_dir }}/kubernetic"
    extra_opts: [--strip-components=1]

- name: Kubernetic | Install
  copy:
    src: "{{ setup_dir }}/kubernetic"
    dest: "/opt"
  become: true

- name: Kubernetic | Set executable
  file:
    path: /opt/kubernetic/kubernetic
    mode: a+x
  become: true

- name: Kubernetic | Create Desktop Icon
  copy:
    src: applications/kubernetic.desktop
    dest: "{{ applications_dir }}/kubernetic.desktop"
