- name: Helm | Get release
  github_release:
    user: kubernetes-sigs
    repo: kustomize
    action: latest_release
    token: "{{ github_token }}"
  register: kustomize_release

- name: Kustomize | Download Archive
  unarchive:
    src: "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize_v3.5.5/kustomize_v3.5.5_linux_amd64.tar.gz"
    remote_src: true
    dest: "{{ setup_dir }}/helm"
