name: CI

on:
  push:
    branches:
      - main
  pull_request:
      branches:
        - main
  workflow_dispatch:

defaults:
  run:
    working-directory: ./provision
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x  # Use the desired Python version

    - name: Install Dependencies
      run: |
        python3 -m venv .venv && source .venv/bin/activate
        pip install -r requirements.txt

    - name: Run Ansible Lint
      run: ansible-lint playbooks/setup.yml roles

    - name: Check Syntax
      run: ansible-playbook --syntax-check playbooks/*.yml

